### ISSUE TITLE
Missing command about how to run this thing...

### ISSUE THREAD

**Issue by sebras** [Epigenetic/johnniac_emulation#1]
I have never used Typescript but I want to try your emu. Run command in Linux is not a problem at all, but after having installed tsc and jest I  just get "unknown token export" when running "tsc && npm run test" so now I'm stuck.

Perhaps a section or two in the README could help me to run this thing? :)

**Comment by Epigenetic** [comment]
I've made a PR (#2) with some more instructions. Please take a look if you can and let me know if those work for you.
